display_name: Lex
package_name: lex
maintainer:
  name: liuyuxin
  email: gvenusleo@gmail.com
priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/logo.png

dependencies:
  - libkeybinder-3.0-0
  - libayatana-appindicator3-dev
  - libnotify-dev
  - libkeybinder-3.0-dev
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-bad
  - python3-tk
  - python3-dev

postinstall_scripts:
  - echo "------------------- Welcom to Lex -------------------\n  @website   https://lex-app.cn\n  @github    https://github.com/gvenusleo/lex-app\n  @author    liuyuxin\n  @email     gvenusleo@gmail.com\n---------------------------------------------------"
postuninstall_scripts:
  - echo "------------------------ Lex ------------------------\n  @website   https://lex-app.cn\n  @github    https://github.com/gvenusleo/lex-app\n  @author    liuyuxin\n  @email     gvenusleo@gmail.com\n---------------------------------------------------"

keywords:
  - Translatiion
  - OCR
  - Application

generic_name: Translation & OCR Application

categories:
  - Utility

startup_notify: true
